### ISSUE TITLE
redshift schema dumping failing

### ISSUE THREAD

**Issue by bradrobertson** [influitive/blueshift#13]
± br |br/group_contact_company_id ✓| → rake redshift:schema:dump
rake aborted!
Sequel::DatabaseError: PG::UndefinedColumn: ERROR:  column "name" does not exist
LINE 1: ...ttribute"."attnotnull" AS "allow_null", COALESCE(("name" = '...
                                                             ^
/Users/dev/.rvm/gems/ruby-2.3.0/gems/sequel-4.35.0/lib/sequel/adapters/postgres.rb:186:in `async_exec'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/sequel-4.35.0/lib/sequel/adapters/postgres.rb:186:in `block in execute_query'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/sequel-4.35.0/lib/sequel/database/logging.rb:48:in `log_connection_yield'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/sequel-4.35.0/lib/sequel/adapters/postgres.rb:186:in `execute_query'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/sequel-4.35.0/lib/sequel/adapters/postgres.rb:173:in `block in execute'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/sequel-4.35.0/lib/sequel/adapters/postgres.rb:149:in `check_disconnect_errors'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/sequel-4.35.0/lib/sequel/adapters/postgres.rb:173:in `execute'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/sequel-4.35.0/lib/sequel/adapters/postgres.rb:525:in `_execute'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/sequel-4.35.0/lib/sequel/adapters/postgres.rb:341:in `block (2 levels) in execute'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/sequel-4.35.0/lib/sequel/adapters/postgres.rb:546:in `check_database_errors'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/sequel-4.35.0/lib/sequel/adapters/postgres.rb:341:in `block in execute'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/sequel-4.35.0/lib/sequel/database/connecting.rb:251:in `block in synchronize'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/sequel-4.35.0/lib/sequel/connection_pool/threaded.rb:105:in `hold'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/sequel-4.35.0/lib/sequel/database/connecting.rb:251:in `synchronize'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/sequel-4.35.0/lib/sequel/adapters/postgres.rb:341:in `execute'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/sequel-4.35.0/lib/sequel/dataset/actions.rb:970:in `execute'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/sequel-4.35.0/lib/sequel/adapters/postgres.rb:669:in `fetch_rows'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/sequel-4.35.0/lib/sequel/dataset/actions.rb:141:in `each'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/sequel-4.35.0/lib/sequel/dataset/actions.rb:392:in `map'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/sequel-4.35.0/lib/sequel/dataset/actions.rb:392:in `map'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/blue-shift-0.3.1/lib/sequel/adapters/redshift.rb:109:in `schema_parse_table'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/sequel-4.35.0/lib/sequel/database/query.rb:161:in `schema'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/sequel-4.35.0/lib/sequel/extensions/schema_dumper.rb:246:in `dump_table_generator'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/blue-shift-0.3.1/lib/sequel/extensions/redshift_schema_dumper.rb:10:in `dump_table_schema'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/sequel-4.35.0/lib/sequel/extensions/schema_dumper.rb:138:in `block in dump_schema_migration'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/sequel-4.35.0/lib/sequel/extensions/schema_dumper.rb:138:in `map'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/sequel-4.35.0/lib/sequel/extensions/schema_dumper.rb:138:in `dump_schema_migration'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/blue-shift-0.3.1/lib/tasks/schema.rake:51:in `block (4 levels) in <top (required)>'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/blue-shift-0.3.1/lib/tasks/schema.rake:51:in `open'
/Users/dev/.rvm/gems/ruby-2.3.0/gems/blue-shift-0.3.1/lib/tasks/schema.rake:51:in `block (3 levels) in <top (required)>'
/Users/dev/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/dev/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
PG::UndefinedColumn: ERROR:  column "name" does not exist
LINE 1: ...ttribute"."attnotnull" AS "allow_null", COALESCE(("name" = '...

**Comment by bradrobertson** [comment]
I, [2016-06-02T15:04:57.360807 #61794]  INFO -- : (0.000801s) SELECT NULL AS "nil" FROM "schema_migrations" LIMIT 1
I, [2016-06-02T15:04:57.361313 #61794]  INFO -- : (0.000198s) SELECT * FROM "schema_migrations" LIMIT 1
I, [2016-06-02T15:04:57.362464 #61794]  INFO -- : (0.000748s) SELECT "filename" FROM "schema_migrations" ORDER BY "filename"
I, [2016-06-02T15:04:57.363469 #61794]  INFO -- : Begin applying migration 20160531163554_reapply_sortkeys.rb, direction: up
I, [2016-06-02T15:04:57.364015 #61794]  INFO -- : (0.000316s) BEGIN
E, [2016-06-02T15:04:57.365956 #61794] ERROR -- : PG::UndefinedColumn: ERROR:  column "name" does not exist
LINE 1: ...ttribute"."attnotnull" AS "allow_null", COALESCE(("name" = '...
                                                             ^: 

```SELECT "pg_attribute"."attname" AS "name", CAST("pg_attribute"."atttypid" AS integer) AS "oid", CAST("basetype"."oid" AS integer) AS "base_oid", format_type("basetype"."oid", "pg_type"."typtypmod") AS "db_base_type", format_type("pg_type"."oid", "pg_attribute"."atttypmod") AS "db_type", pg_get_expr("pg_attrdef"."adbin", "pg_class"."oid") AS "default", NOT "pg_attribute"."attnotnull" AS "allow_null", COALESCE(("name" = 'id'), false) AS "primary_key" FROM "pg_class" INNER JOIN "pg_attribute" ON ("pg_attribute"."attrelid" = "pg_class"."oid") INNER JOIN "pg_type" ON ("pg_type"."oid" = "pg_attribute"."atttypid") LEFT OUTER JOIN "pg_type" AS "basetype" ON ("basetype"."oid" = "pg_type"."typbasetype") LEFT OUTER JOIN "pg_attrdef" ON (("pg_attrdef"."adrelid" = "pg_class"."oid") AND ("pg_attrdef"."adnum" = "pg_attribute"."attnum")) LEFT OUTER JOIN "pg_index" ON (("pg_index"."indrelid" = "pg_class"."oid") AND ("pg_index"."indisprimary" IS TRUE)) WHERE (("pg_attribute"."attisdropped" IS FALSE) AND ("pg_attribute"."attnum" > 0) AND ("pg_class"."oid" = CAST(CAST('"companies"' AS regclass) AS oid))) ORDER BY "pg_attribute"."attnum"```

I, [2016-06-02T15:04:57.366461 #61794]  INFO -- : (0.000082s) ROLLBACK
rake aborted!
Sequel::DatabaseError: PG::UndefinedColumn: ERROR:  column "name" does not exist
LINE 1: ...ttribute"."attnotnull" AS "allow_null", COALESCE(("name" = '...
                                                             ^

**Comment by bradrobertson** [comment]
Duplicated with #15
